// Package header provides the constants for HTTP headers.
package header

import (
	"net/textproto"
)

// Header is type definition of a HTTP header.
type Header string

// String returns string representation of the header, canonicalised
// by textproto.CanonicalMIMEHeaderKey.
func (h Header) String() string {
	return textproto.CanonicalMIMEHeaderKey(string(h))
}

// Common HTTP headers as defined by Mozilla.
// https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers
const (
	AcceptCHLifetime                Header = "Accept-CH-Lifetime"
	AcceptCH                        Header = "Accept-CH"
	AcceptCharset                   Header = "Accept-Charset"
	AcceptEncoding                  Header = "Accept-Encoding"
	AcceptLanguage                  Header = "Accept-Language"
	AcceptPatch                     Header = "Accept-Patch"
	AcceptPost                      Header = "Accept-Post"
	AcceptRanges                    Header = "Accept-Ranges"
	Accept                          Header = "Accept"
	AccessControlAllowCredentials   Header = "Access-Control-Allow-Credentials"
	AccessControlAllowHeaders       Header = "Access-Control-Allow-Headers"
	AccessControlAllowMethods       Header = "Access-Control-Allow-Methods"
	AccessControlAllowOrigin        Header = "Access-Control-Allow-Origin"
	AccessControlExposeHeaders      Header = "Access-Control-Expose-Headers"
	AccessControlMaxAge             Header = "Access-Control-Max-Age"
	AccessControlRequestHeaders     Header = "Access-Control-Request-Headers"
	AccessControlRequestMethod      Header = "Access-Control-Request-Method"
	Age                             Header = "Age"
	Allow                           Header = "Allow"
	AltSvc                          Header = "Alt-Svc"
	Authorization                   Header = "Authorization"
	CacheControl                    Header = "Cache-Control"
	ClearSiteData                   Header = "Clear-Site-Data"
	Connection                      Header = "Connection"
	ContentDisposition              Header = "Content-Disposition"
	ContentEncoding                 Header = "Content-Encoding"
	ContentLanguage                 Header = "Content-Language"
	ContentLength                   Header = "Content-Length"
	ContentLocation                 Header = "Content-Location"
	ContentRange                    Header = "Content-Range"
	ContentSecurityPolicyReportOnly Header = "Content-Security-Policy-Report-Only"
	ContentSecurityPolicy           Header = "Content-Security-Policy"
	ContentType                     Header = "Content-Type"
	Cookie                          Header = "Cookie"
	Cookie2                         Header = "Cookie2"
	CrossOriginEmbedderPolicy       Header = "Cross-Origin-Embedder-Policy"
	CrossOriginOpenerPolicy         Header = "Cross-Origin-Opener-Policy"
	CrossOriginResourcePolicy       Header = "Cross-Origin-Resource-Policy"
	Date                            Header = "Date"
	DeviceMemory                    Header = "Device-Memory"
	Digest                          Header = "Digest"
	DNT                             Header = "DNT"
	DPR                             Header = "DPR"
	EarlyData                       Header = "Early-Data"
	ETag                            Header = "ETag"
	ExpectCT                        Header = "Expect-CT"
	Expect                          Header = "Expect"
	Expires                         Header = "Expires"
	FeaturePolicy                   Header = "Feature-Policy"
	Forwarded                       Header = "Forwarded"
	From                            Header = "From"
	Host                            Header = "Host"
	IfMatch                         Header = "If-Match"
	IfModifiedSince                 Header = "If-Modified-Since"
	IfNoneMatch                     Header = "If-None-Match"
	IfRange                         Header = "If-Range"
	IfUnmodifiedSince               Header = "If-Unmodified-Since"
	Index                           Header = "Index"
	KeepAlive                       Header = "Keep-Alive"
	LargeAllocation                 Header = "Large-Allocation"
	LastModified                    Header = "Last-Modified"
	Link                            Header = "Link"
	Location                        Header = "Location"
	NEL                             Header = "NEL"
	Origin                          Header = "Origin"
	Pragma                          Header = "Pragma"
	ProxyAuthenticate               Header = "Proxy-Authenticate"
	ProxyAuthorization              Header = "Proxy-Authorization"
	PublicKeyPinsReportOnly         Header = "Public-Key-Pins-Report-Only"
	PublicKeyPins                   Header = "Public-Key-Pins"
	Range                           Header = "Range"
	Referer                         Header = "Referer"
	ReferrerPolicy                  Header = "Referrer-Policy"
	RetryAfter                      Header = "Retry-After"
	SaveData                        Header = "Save-Data"
	SecFetchDest                    Header = "Sec-Fetch-Dest"
	SecFetchMode                    Header = "Sec-Fetch-Mode"
	SecFetchSite                    Header = "Sec-Fetch-Site"
	SecFetchUser                    Header = "Sec-Fetch-User"
	SecWebSocketAccept              Header = "Sec-WebSocket-Accept"
	ServerTiming                    Header = "Server-Timing"
	Server                          Header = "Server"
	SetCookie                       Header = "Set-Cookie"
	SetCookie2                      Header = "Set-Cookie2"
	SourceMap                       Header = "SourceMap"
	StrictTransportSecurity         Header = "Strict-Transport-Security"
	TE                              Header = "TE"
	TimingAllowOrigin               Header = "Timing-Allow-Origin"
	Tk                              Header = "Tk"
	Trailer                         Header = "Trailer"
	TransferEncoding                Header = "Transfer-Encoding"
	UpgradeInsecureRequests         Header = "Upgrade-Insecure-Requests"
	Upgrade                         Header = "Upgrade"
	UserAgent                       Header = "User-Agent"
	Vary                            Header = "Vary"
	Via                             Header = "Via"
	WantDigest                      Header = "Want-Digest"
	Warning                         Header = "Warning"
	WWWAuthenticate                 Header = "WWW-Authenticate"
	XContentTypeOptions             Header = "X-Content-Type-Options"
	XDNSPrefetchControl             Header = "X-DNS-Prefetch-Control"
	XForwardedFor                   Header = "X-Forwarded-For"
	XForwardedHost                  Header = "X-Forwarded-Host"
	XForwardedProto                 Header = "X-Forwarded-Proto"
	XFrameOptions                   Header = "X-Frame-Options"
	XXSSProtection                  Header = "X-XSS-Protection"
)
