name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-golang:
    name: Test on Go ${{ matrix.go }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: 3
    strategy:
      matrix:
        os:
          # NOTE: Non-linux systems uses more billable minutes.
          # Enable them only if they are strictly required.
          # - windows-latest
          # - macos-latest
          - ubuntu-latest
        go:
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'

    steps:
      - name: Checkout branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: ${{ matrix.go }}

      - name: Lint code
        run: |
          make lint

      - name: Validate code
        run: |
          make check

      - name: Run tests
        run: |
          make test
